filetype on
syntax on

set number
set showcmd
set wildmenu
set wrap

let skip_defaults=1
set viminfo=""

set cursorline
 hi cursorline cterm=none term=none 
 highlight CursorLine guibg=#303000 ctermbg=234

set tabstop=4


call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()
