"""" BASIC CONFIG
set number
set showcmd
set wildmenu
set wrap
set linebreak

colorscheme industry_b
set cursorline
 hi cursorline cterm=none term=none 
" highlight CursorLine guibg=#303030 ctermbg=234


"""" VIM FILE MANAGEMENT
let skip_defaults=1
set viminfo=""


"""" FILETYPE DEPENDENT OPTIONS
syntax off
filetype off
filetype plugin on
filetype indent off
set autoindent
set noexpandtab
autocmd FileType python setlocal noexpandtab

"""" VIM STATUS BAR CHANGES
set laststatus=2 " show the statuslineendfunction

let g:word_count=wordcount().words
function WordCount()
    if has_key(wordcount(),'visual_words')
        let g:word_count=wordcount().visual_words."/".wordcount().words " count selected words
    else
        let g:word_count=wordcount().cursor_words."/".wordcount().words " or shows words 'so far'
    endif
    return g:word_count
endfunction

hi StatusLine guibg=Black ctermfg=0 guifg=Black ctermbg=0
set statusline=
set statusline+=\ [%F]\ 
set statusline+=%=
set statusline+=\ (%l,%c)\ -\ [%{WordCount()}]\ 

set visualbell

"""" VIM PLUGINS
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
call plug#end()
